### ISSUE TITLE
test.sh error

### ISSUE THREAD

**Issue by lingtran** [drew-t/rush-hour#42]
Following error occurred when running test script for curl requests:

Already Received RequestHTTP/1.1 500 Internal Server Error
Content-Type: text/plain
Content-Length: 8392
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Sun, 03 Apr 2016 03:18:33 GMT
Connection: Keep-Alive

ActiveRecord::StatementInvalid: PG::InvalidTextRepresentation: ERROR:  invalid input syntax for type inet: "63.29.33.322"
: SELECT  "ips".* FROM "ips" WHERE "ips"."ip" = $1 LIMIT 1
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `exec_prepared'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:602:in `block in exec_cache'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:472:in `block in log'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activesupport-4.2.5.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract_adapter.rb:466:in `log'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:601:in `exec_cache'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql_adapter.rb:585:in `execute_and_clear'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/postgresql/database_statements.rb:160:in `exec_query'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:355:in `select'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/database_statements.rb:32:in `select_all'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/connection_adapters/abstract/query_cache.rb:70:in `select_all'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:39:in `find_by_sql'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:639:in `exec_queries'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:515:in `load'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:243:in `to_a'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/finder_methods.rb:475:in `find_take'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/finder_methods.rb:105:in `take'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation/finder_methods.rb:84:in `find_by'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/relation.rb:213:in `find_or_create_by'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/activerecord-4.2.5.1/lib/active_record/querying.rb:6:in `find_or_create_by'
	/Users/lingtran/turing/2module/rush-hour/app/models/payload_creator.rb:28:in `create_ip'
	/Users/lingtran/turing/2module/rush-hour/app/models/payload_creator.rb:46:in `create_payload'
	/Users/lingtran/turing/2module/rush-hour/app/controllers/server.rb:39:in `block in <class:Server>'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1610:in `block in compile!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (3 levels) in route!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:994:in `route_eval'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:975:in `block (2 levels) in route!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1015:in `block in process_route'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `catch'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1013:in `process_route'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:973:in `block in route!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `each'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:972:in `route!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1085:in `block in dispatch!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1082:in `dispatch!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `block in call!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `block in invoke'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `catch'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1067:in `invoke'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:907:in `call!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:895:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/xss_header.rb:18:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/path_traversal.rb:16:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/json_csrf.rb:18:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/base.rb:49:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-protection-1.5.3/lib/rack/protection/frame_options.rb:31:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/nulllogger.rb:9:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/head.rb:13:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/methodoverride.rb:22:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/show_exceptions.rb:25:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:182:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:2013:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `block in call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1787:in `synchronize'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:1487:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:49:in `_call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/lint.rb:37:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/showexceptions.rb:24:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/commonlogger.rb:33:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/sinatra-1.4.7/lib/sinatra/base.rb:219:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:86:in `proceed_as_child'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:31:in `call!'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shotgun-0.9.1/lib/shotgun/loader.rb:18:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/shotgun-0.9.1/lib/shotgun/favicon.rb:12:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:66:in `block in call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `each'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/urlmap.rb:50:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/builder.rb:153:in `call'
	/Users/lingtran/.rvm/gems/ruby-2.3.0/gems/rack-1.6.4/lib/rack/handler/webrick.rb:88:in `service'
	/Users/lingtran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:140:in `service'
	/Users/lingtran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/httpserver.rb:96:in `run'
	/Users/lingtran/.rvm/rubies/ruby-2.3.0/lib/ruby/2.3.0/webrick/server.rb:296:in `block in start_thread'HTTP/1.1 403 Forbidden
Content-Type: text/html;charset=utf-8
Content-Length: 24
X-Xss-Protection: 1; mode=block
X-Content-Type-Options: nosniff
X-Frame-Options: SAMEORIGIN
Server: WEBrick/1.3.1 (Ruby/2.3.0/2015-12-25)
Date: Sun, 03 Apr 2016 03:18:34 GMT
Connection: Keep-Alive

**Comment by lingtran** [comment]
when going to identifier/client pages, following identifiers were erroring:

turing, microsoft, yahoo, apple, palantir, facebook

reason:  nil in client?
